### ISSUE TITLE
Tracking: New README Header Style

### ISSUE THREAD

**Issue by celialewis3** [EmbarkStudios/opensource-template#36]
A tracking issue to track which opensource repositories have been successfully converted to the new README style detailed in #33 

- [x] cargo-deny
- [x] puffin
- [ ] lmdb-rs
- [ ] rkv
- [ ] rpmalloc-rs
- [ ] blender_addons
- [ ] aws-lambda-rust-runtime
- [ ] cassini
- [ ] cos-gpu-installer
- [ ] container-engine-accelerators
- [ ] gltf
- [ ] imgui-rs
- [ ] gke-accelerated-xorg-example
- [ ] kubekite
- [ ] vk-mem-rs
- [ ] Unreal.js-core
- [ ] urdf-rs
- [ ] helix-oidc
- [ ] rust-multibase
- [ ] rust-ecosystem
- [ ] wasmer
- [ ] buildkite-jobify
- [ ] tower-http
- [ ] dialoguer
- [ ] tower-grpc
- [ ] kubernetes-rust
- [ ] wg-ui
- [ ] istio
- [ ] ash-molten
- [ ] reqwest
- [ ] actix-web
- [ ] k8s-buildkite-plugin
- [ ] tokio
- [ ] container-packer-qemu
- [ ] coreaudio-sys
- [ ] wasmparser.rs
- [ ] cranelift
- [ ] tower-hyper
- [ ] winit
- [ ] glam-rs
- [ ] cpal
- [ ] serde-xml-rs
- [ ] sentry-rust
- [ ] InfraworldRuntime
- [ ] tensorflow-onnx
- [ ] netboot.xyz
- [ ] nativefiledialog
- [ ] tame-oauth
- [ ] physx-rs
- [ ] nfd-rs
- [ ] opensource-template
- [ ] tame-gcs
- [ ] zbox
- [ ] serde_urlencoded
- [ ] Python-xNormal
- [ ] cargo-fetcher
- [ ] color-backtrace
- [ ] infraworld-cornerstone
- [ ] webbrowser-rs
- [ ] colored
- [ ] texture-synthesis
- [ ] spdx
- [ ] flamegraph
- [ ] img_hash
- [ ] opensource-website
- [ ] rust-embed-resource
- [ ] iovec
- [ ] app_dirs2
- [ ] PhysX
- [ ] mockito
- [ ] agones
- [ ] enumflags2
- [ ] anyhow
- [ ] docker-pyinstaller
- [ ] ring
- [ ] page_size_rs
- [ ] .github
- [ ] prost
- [ ] raw-window-handle
- [ ] sccache
- [ ] cargo-about
- [ ] tonic
- [ ] prom2hny
- [ ] istio-api
- [ ] KantanCharts
- [ ] vscode-unreal-angelscript
- [ ] blender-tools
- [ ] smush-rs
- [ ] legion
- [ ] cargo-deny-action
- [ ] docker-devpi
- [ ] advisory-db
- [ ] concaveman-cpp
- [ ] shaderc-rs
- [ ] missing-symbols
- [ ] cfg-expr
- [ ] rust
- [ ] krates
- [ ] keyring-rs
- [ ] rules_helm
- [ ] include_dir
- [ ] lewton
- [ ] imgui-inspect
- [ ] superluminal-perf-rs
- [ ] UE4StateMachineExPlugin
- [ ] service
- [ ] nfd2
- [ ] juniper
- [ ] ImpostorBaker
- [ ] labeler
- [ ] automerge-action
- [ ] review-action
- [ ] mimalloc_rust
- [ ] deepspeech-rs
- [ ] bson-rust
- [ ] wayland-rs
- [ ] rust-postgres
- [ ] wasmtime
- [ ] symbolicator
- [ ] target-lexicon
- [ ] sentry-native
- [ ] flatbuffers
- [ ] xxhrs
- [ ] rust-gpu
- [ ] cargo_metadata
- [ ] tract
- [ ] cc-rs
- [ ] BLAKE3
- [ ] cargo-outdated
- [ ] rustsec-crate
- [ ] rust-crates-index
- [ ] cargo
- [ ] prefabricator-ue4
- [ ] rust-gamedev.github.io
- [ ] opensource
- [ ] spirv-tools-rs
- [ ] wasi-test
- [ ] SPIRV-Tools
- [ ] relnotes
- [ ] secret-service-rs
- [ ] opa-policies
- [ ] stacker
- [ ] tryhard
- [ ] sentry-contrib-rust
- [ ] HoudiniEngineForUnreal-v2
- [ ] breakpad
- [ ] golang-pkg-browser
- [ ] rspirv
- [ ] grafana-cortex-tools
- [ ] alsa-rs
- [ ] rust-cexpr
- [ ] grafonnet-lib
- [ ] winapi-rs
- [ ] skyhook
- [ ] octobors
- [ ] rpmalloc
- [ ] naga
- [ ] metrics
- [ ] octocrab
- [ ] tracing
- [ ] gsutil
- [ ] rapier
- [ ] emojis
- [ ] schannel-rs
- [ ] tame-oidc
- [ ] sqlx
- [ ] hashbrown
- [ ] nalgebra
- [ ] jsonwebtoken
- [ ] parry
- [ ] Feather
- [ ] fork-daichirata-hammer
- [ ] fork-bazelbuild-rules_go
- [ ] go-buildkite
- [ ] ash
- [ ] rust_serialization_benchmark
- [ ] vk-sync-rs
- [ ] UE4-EditorScriptingToolsPlugin
- [ ] discord_game_sdk
- [ ] rules_k8s
- [ ] rspirv-reflect
- [ ] gpu-allocator
- [ ] symbolic
- [ ] wasmbin
- [ ] discord-sdk
- [ ] discord-api-docs
- [ ] mio
- [ ] grafana
- [ ] spirv-reflect-rs
- [ ] rymder
- [ ] rust_tracy_client
- [ ] rfd
- [ ] pubnub_go
- [ ] kube-rs
- [ ] annotator-buildkite-plugin

**Comment by repi** [comment]
closing this as it is stale and it doesn't list our projects but also all of our forks which we do not control and shouldn't update.
